name: Docker CI Pipeline

# Trigger: Menjalankan workflow setiap kali ada push ke branch "main"
on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          # PASTIKAN PATH INI BENAR menunjuk ke folder yang berisi Dockerfile
          context: ./proyek-ular-tangga
          push: true
          # --- INI BAGIAN YANG DIPERBAIKI ---
          # Format yang benar dan aman, menggunakan nama owner repo dan nama repo
          tags: ghcr.io/${{ github.repository_owner }}/proyek-docker:latest
