name: Docker CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          # Pastikan path ini benar menunjuk ke folder yang berisi Dockerfile
          context: ./proyek-ular-tangga 
          push: true
          # --- SOLUSI PASTI ---
          # Menggunakan username Anda yang sudah ditulis manual dalam huruf kecil
          tags: ghcr.io/muhamadnabil-28/proyek-docker:latest
